# Generated by Django 4.2.30 on 2026-06-26 18:01

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('length', models.DecimalField(decimal_places=2, help_text='Internal length in centimeters.', max_digits=8, validators=[core.validators.validate_positive_decimal])),
                ('width', models.DecimalField(decimal_places=2, help_text='Internal width in centimeters.', max_digits=8, validators=[core.validators.validate_positive_decimal])),
                ('height', models.DecimalField(decimal_places=2, help_text='Internal height in centimeters.', max_digits=8, validators=[core.validators.validate_positive_decimal])),
                ('max_weight_capacity', models.DecimalField(decimal_places=3, help_text='Maximum weight capacity in kilograms.', max_digits=8, validators=[core.validators.validate_positive_decimal])),
                ('cost', models.DecimalField(decimal_places=2, help_text='Shipping box cost.', max_digits=8, validators=[core.validators.validate_positive_decimal])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'shipping box',
                'verbose_name_plural': 'shipping boxes',
                'ordering': ['cost', 'box_code'],
            },
        ),
    ]
