# Generated by Django 4.2.30 on 2026-06-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingbox',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
