# Generated by Django 4.2.30 on 2026-06-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('required_length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('required_width', models.DecimalField(decimal_places=2, max_digits=8)),
                ('required_height', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('success', 'Success'), ('no_suitable_box', 'No Suitable Box Available')], db_index=True, max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='orders.order')),
                ('recommended_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='boxes.shippingbox')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
