# Generated by Django 4.2.30 on 2026-06-26 18:01

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[core.validators.validate_non_negative_decimal])),
                ('length', models.DecimalField(decimal_places=2, help_text='Length in centimeters.', max_digits=8, validators=[core.validators.validate_positive_decimal])),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in centimeters.', max_digits=8, validators=[core.validators.validate_positive_decimal])),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in centimeters.', max_digits=8, validators=[core.validators.validate_positive_decimal])),
                ('weight', models.DecimalField(decimal_places=3, help_text='Weight in kilograms.', max_digits=8, validators=[core.validators.validate_positive_decimal])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='products_pr_categor_226e74_idx')],
            },
        ),
    ]
